# Generated by Django 5.2.4 on 2025-08-22 05:09

import django.contrib.postgres.fields
import django.utils.timezone
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('product_id', models.CharField(default=orders.models.generate_product_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('fabric_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fabric_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('colours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', '2X Large'), ('3XL', '3X Large')], max_length=4), blank=True, default=list, size=None)),
                ('size_quantities', models.JSONField(blank=True, default=dict)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('cutting', 'In Progress'), ('stitching', 'In Progress'), ('finishing', 'In Progress'), ('Ready for Delivery', 'Ready for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
            ],
        ),
    ]
