# Generated by Django 5.2.4 on 2025-09-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='set_multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
