// src/types/order.ts
export type OrderStatus = 
  | "Pending" 
  | "cutting" 
  | "stitching" 
  | "finishing"
  | "Ready for Delivery" 
  | "Delivered" 
  | "Cancelled"; // Fixed: "cancelled" → "Cancelled" to match backend

export interface Order {
  product_id: string;
  customer_name: string;
  product_name: string;
  product_image?: string | File | null;
  order_date: string;
  delivery_date: string;
  status: OrderStatus;
  quantity: number;
  size: string[]; // Changed from optional to required (matches backend default)
  size_quantities: Record<string, number | null>;
  fabric_type?: string;
  fabric_weight?: string;
  colours: string[]; // Changed from optional to required (matches backend default)
  description?: string;
  is_set: boolean;
  set_multiplier: number;
}

// Helper types for creating new entities and updates
// For creation, omit fields generated by backend (product_id, order_date, created_at, id)
export type CreateOrderData = Omit<Order, 'product_id' | 'order_date' | 'created_at' | 'id'>;
// For updates, require product_id and allow partial updates to other fields
export type UpdateOrderData = Partial<Omit<Order, 'product_id'>> & { product_id: string };